### ISSUE TITLE
Add a clear license

### ISSUE THREAD

**Issue by ruohola** [MrMrRobat/parametrize#3]
The pyproject file states the license to be MIT: https://github.com/MrMrRobat/parametrize/blob/3cd327e9c1ae4e2dbbf2c30990ed405a9fb2448e/pyproject.toml#L6 but I would suggest adding an explicit `LICENSE` file to the project as well, which contains the text for the MIT license. Otherwise pretty much no one should use this library.

**Comment by Bobronium** [comment]
@ruohola, sure! Feel free to open PR that adds MIT license file. I'll hit the merge button 😄
