### ISSUE TITLE
Differences to parameterized ?

### ISSUE THREAD

**Issue by stuaxo** [MrMrRobat/parametrize#5]
Parameterized has been around for a while, are there any differences to it ?
https://github.com/wolever/parameterized

It's a bit confusing as it's easy to end up on this project on pypi, when users may be aiming for the other one.

**Comment by Bobronium** [comment]
Have you read through readme of this project before opening the issue?

**Comment by stuaxo** [comment]
I did, but maybe not closely enough ?   It seems like I can use both on unittest Tests, I haven't really tried testing stuff like cython, so not familiar with limitations there.

TBH, I've spent a couple of years on a pytest based project and just coming back to python unittest, so bound to be missing alot.

**Comment by Bobronium** [comment]
Compared to other projects, `parametrize` is backwards compatible with `pytest.mark.parametrize` and support parametrization through stacking decorators on one another, resulting in product of parameters and their values of these decorators (which also replicates behavior of `pytest.mark.parametrize`)

It also doesn't require any additional setup besides applying decorator(s) to the function or method.

Does this answer your question?
 

If it does, I would appreciate suggestions on improving the readme, so it would answer that question as well.

**Comment by stuaxo** [comment]
Cheers, the issue is probably that although I've used both APIs I can't say I know pytest.parameterised well enough to notice if it's different to parameterized.

I guess this version has better compatibility, I just don't know what the specific things I can do in this that don't work in the other one are.

It might be good to have some explicit examples of things that work in `pytest.mark.parametrize` and not this API but not in `parameterized`.

I have some vague memory of having to use extend in parameterized, but maybe not in pytest?
